INSERT INTO `qn` (`id`,`key`,`type_code`,`body`,`_labels`,`linked_to_id`) VALUES (1,'AGE','NUMERIC','年龄','',NULL);
INSERT INTO `qn` (`id`,`key`,`type_code`,`body`,`_labels`,`linked_to_id`) VALUES (2,'GENDER','RADIO','性别','{"A": "\u7537", "B": "\u5973"}',NULL);
INSERT INTO `qn` (`id`,`key`,`type_code`,`body`,`_labels`,`linked_to_id`) VALUES (3,'BMI','NUMERIC','BMI','',NULL);
INSERT INTO `qn` (`id`,`key`,`type_code`,`body`,`_labels`,`linked_to_id`) VALUES (4,'WAIST','NUMERIC','腰围（厘米）','',NULL);
INSERT INTO `qn` (`id`,`key`,`type_code`,`body`,`_labels`,`linked_to_id`) VALUES (5,'REL','RADIO','你的一级亲属(父母/子女/同父母的兄弟姐妹中2型糖尿病患者','{"6": "\u662f", "0": "\u5426"}',NULL);
INSERT INTO `qn` (`id`,`key`,`type_code`,`body`,`_labels`,`linked_to_id`) VALUES (6,'SIT','RADIO','您是否长时间坐着工作、使用电脑或看电视等','{"A": "\u662f", "B": "\u5426"}',NULL);
INSERT INTO `qn` (`id`,`key`,`type_code`,`body`,`_labels`,`linked_to_id`) VALUES (7,'妊娠糖尿病','RADIO','是否在妊娠期间发现血糖升高或诊断为妊娠期糖尿病','{"A": "\u662f", "C": "\u672a\u66fe\u6000\u5b55", "B": "\u5426"}',NULL);
INSERT INTO `qn` (`id`,`key`,`type_code`,`body`,`_labels`,`linked_to_id`) VALUES (8,'过大婴儿','RADIO','是否生育过出生体重大于4kg的婴儿','{"A": "\u662f", "C": "\u5c1a\u672a\u751f\u80b2", "B": "\u5426"}',NULL);
INSERT INTO `qn` (`id`,`key`,`type_code`,`body`,`_labels`,`linked_to_id`) VALUES (9,'检测血糖','RADIO','您是否曾经检查过血糖','{"B": "\u5426", "A": "\u662f"}',NULL);
INSERT INTO `qn` (`id`,`key`,`type_code`,`body`,`_labels`,`linked_to_id`) VALUES (10,'空腹血糖','NUMERIC','最高空腹血糖（nmol/L）','',NULL);
INSERT INTO `qn` (`id`,`key`,`type_code`,`body`,`_labels`,`linked_to_id`) VALUES (11,'检查血压','RADIO','您是否曾经检查过血压','{"A": "\u662f", "B": "\u5426"}',NULL);
INSERT INTO `qn` (`id`,`key`,`type_code`,`body`,`_labels`,`linked_to_id`) VALUES (12,'最高血压1','NUMERIC','收缩压（高压）','',13);
INSERT INTO `qn` (`id`,`key`,`type_code`,`body`,`_labels`,`linked_to_id`) VALUES (13,'最高血压2','NUMERIC','舒张压（低压）','',NULL);
INSERT INTO `qn` (`id`,`key`,`type_code`,`body`,`_labels`,`linked_to_id`) VALUES (14,'血脂','RADIO','您是否曾经检查过血脂','{"A": "\u662f", "B": "\u5426"}',NULL);
INSERT INTO `qn` (`id`,`key`,`type_code`,`body`,`_labels`,`linked_to_id`) VALUES (15,'血脂偏高','RADIO','您的血脂偏高么？','{"A": "\u662f", "C": "\u4e0d\u6e05\u695a", "B": "\u5426"}',NULL);
INSERT INTO `qn` (`id`,`key`,`type_code`,`body`,`_labels`,`linked_to_id`) VALUES (16,'其他疾病','RADIO','你是否曾诊断患有冠心病或脑血管疾病','{"A": "\u662f", "B": "\u5426"}',NULL);
INSERT INTO `qn` (`id`,`key`,`type_code`,`body`,`_labels`,`linked_to_id`) VALUES (17,'卵巢','RADIO','是否曾诊断患有多囊卵巢综合症','{"A": "\u662f", "B": "\u5426"}',NULL);
INSERT INTO `qn` (`id`,`key`,`type_code`,`body`,`_labels`,`linked_to_id`) VALUES (18,'药物治疗','RADIO','你是否正在接受以下任何一项药物治疗','{"A": "\u662f", "B": "\u5426"}',NULL);
INSERT INTO `qn` (`id`,`key`,`type_code`,`body`,`_labels`,`linked_to_id`) VALUES (19,'餐后血糖','NUMERIC','最高餐后两小时血糖（nmol/L）','',NULL);
INSERT INTO `qn` (`id`,`key`,`type_code`,`body`,`_labels`,`linked_to_id`) VALUES (20,'WAIST_F','NUMERIC','腰围（厘米）','',NULL);
INSERT INTO `qnr` (`id`,`key`,`name`,`description`) VALUES (1,'ADULT','糖尿病人高位人群自我筛查问卷','成人版');
INSERT INTO `q_asso` (`questionnaire_id`,`question_id`,`sequence`,`_rules`,`rule_type`) VALUES (1,1,1,'{"0": [19, 25], "15": [55, 60], "11": [40, 45], "13": [50, 55], "16": [60, 65], "12": [45, 50], "8": [35, 40], "18": [65, 75], "4": [25, 35]}','R');
INSERT INTO `q_asso` (`questionnaire_id`,`question_id`,`sequence`,`_rules`,`rule_type`) VALUES (1,2,2,'{"A": 2, "B": 0}','M');
INSERT INTO `q_asso` (`questionnaire_id`,`question_id`,`sequence`,`_rules`,`rule_type`) VALUES (1,3,3,'{"0": [0, 22], "5": [30], "3": [24, 30], "1": [22, 24]}','R');
INSERT INTO `q_asso` (`questionnaire_id`,`question_id`,`sequence`,`_rules`,`rule_type`) VALUES (1,4,5,'{"0": [0, 75], "3": [75, 80], "5": [80, 85], "10": [95], "7": [85, 90], "8": [90, 95]}','R');
INSERT INTO `q_asso` (`questionnaire_id`,`question_id`,`sequence`,`_rules`,`rule_type`) VALUES (1,5,6,NULL,'N');
INSERT INTO `q_asso` (`questionnaire_id`,`question_id`,`sequence`,`_rules`,`rule_type`) VALUES (1,6,7,NULL,'N');
INSERT INTO `q_asso` (`questionnaire_id`,`question_id`,`sequence`,`_rules`,`rule_type`) VALUES (1,7,8,NULL,'N');
INSERT INTO `q_asso` (`questionnaire_id`,`question_id`,`sequence`,`_rules`,`rule_type`) VALUES (1,8,9,NULL,'N');
INSERT INTO `q_asso` (`questionnaire_id`,`question_id`,`sequence`,`_rules`,`rule_type`) VALUES (1,9,10,NULL,'N');
INSERT INTO `q_asso` (`questionnaire_id`,`question_id`,`sequence`,`_rules`,`rule_type`) VALUES (1,10,11,NULL,'N');
INSERT INTO `q_asso` (`questionnaire_id`,`question_id`,`sequence`,`_rules`,`rule_type`) VALUES (1,11,13,NULL,'N');
INSERT INTO `q_asso` (`questionnaire_id`,`question_id`,`sequence`,`_rules`,`rule_type`) VALUES (1,12,14,'{"0": [0, 110], "3": [120, 130], "1": [110, 120], "6": [130, 140], "7": [140, 150], "8": [150, 160], "10": [160]}','R');
INSERT INTO `q_asso` (`questionnaire_id`,`question_id`,`sequence`,`_rules`,`rule_type`) VALUES (1,14,15,NULL,'N');
INSERT INTO `q_asso` (`questionnaire_id`,`question_id`,`sequence`,`_rules`,`rule_type`) VALUES (1,15,16,NULL,'N');
INSERT INTO `q_asso` (`questionnaire_id`,`question_id`,`sequence`,`_rules`,`rule_type`) VALUES (1,16,17,NULL,'N');
INSERT INTO `q_asso` (`questionnaire_id`,`question_id`,`sequence`,`_rules`,`rule_type`) VALUES (1,17,18,NULL,'N');
INSERT INTO `q_asso` (`questionnaire_id`,`question_id`,`sequence`,`_rules`,`rule_type`) VALUES (1,18,19,NULL,'N');
INSERT INTO `q_asso` (`questionnaire_id`,`question_id`,`sequence`,`_rules`,`rule_type`) VALUES (1,19,12,NULL,'N');
INSERT INTO `q_asso` (`questionnaire_id`,`question_id`,`sequence`,`_rules`,`rule_type`) VALUES (1,20,4,'{"0": [0, 70], "3": [70, 75], "5": [75, 80], "10": [90], "7": [80, 85], "8": [85, 90]}','R');
INSERT INTO `qz_depend` (`id`,`question_id`,`check_method`,`check_value`,`check_against`,`affecting_all`,`affected_qnr`) VALUES (1,7,'EQ','B','GENDER',1,'');
INSERT INTO `qz_depend` (`id`,`question_id`,`check_method`,`check_value`,`check_against`,`affecting_all`,`affected_qnr`) VALUES (2,8,'EQ','B','GENDER',1,'');
INSERT INTO `qz_depend` (`id`,`question_id`,`check_method`,`check_value`,`check_against`,`affecting_all`,`affected_qnr`) VALUES (3,17,'EQ','B','GENDER',1,'');
INSERT INTO `qz_depend` (`id`,`question_id`,`check_method`,`check_value`,`check_against`,`affecting_all`,`affected_qnr`) VALUES (4,10,'EQ','A','检测血糖',1,'');
INSERT INTO `qz_depend` (`id`,`question_id`,`check_method`,`check_value`,`check_against`,`affecting_all`,`affected_qnr`) VALUES (5,12,'EQ','A','检查血压',1,'');
INSERT INTO `qz_depend` (`id`,`question_id`,`check_method`,`check_value`,`check_against`,`affecting_all`,`affected_qnr`) VALUES (6,15,'EQ','A','血脂',1,'');
INSERT INTO `qz_depend` (`id`,`question_id`,`check_method`,`check_value`,`check_against`,`affecting_all`,`affected_qnr`) VALUES (7,17,'EQ','B','GENDER',1,'');
INSERT INTO `qz_depend` (`id`,`question_id`,`check_method`,`check_value`,`check_against`,`affecting_all`,`affected_qnr`) VALUES (8,4,'EQ','A','GENDER',1,'');
INSERT INTO `qz_depend` (`id`,`question_id`,`check_method`,`check_value`,`check_against`,`affecting_all`,`affected_qnr`) VALUES (9,20,'EQ','B','GENDER',1,'');
INSERT INTO `qz_depend` (`id`,`question_id`,`check_method`,`check_value`,`check_against`,`affecting_all`,`affected_qnr`) VALUES (10,19,'EQ','A','检测血糖',1,'');
INSERT INTO `result_code` (`id`,`text`) VALUES (1,'您是糖尿病高风险人群，建议至正规医院进行口服葡萄糖耐量（OGTT）检查');
INSERT INTO `result_code` (`id`,`text`) VALUES (2,'您是糖尿病前期患者，每年有1.5%-10.0%的糖尿病前期患者进展为2型糖尿病');
INSERT INTO `result_code` (`id`,`text`) VALUES (3,'根据中国2型糖尿病防治指南，您有必要进行糖尿病筛查');
INSERT INTO `result_code` (`id`,`text`) VALUES (4,'您除了年龄≥40岁外，无其他糖尿病危险因素，但根据中国2型糖尿病防治指南，依然建议您从40岁开始进行糖尿病筛查，首次筛查结果正常者，建议至少每3年重复筛查一次');
INSERT INTO `result_code` (`id`,`text`) VALUES (5,'您是儿童青少年糖尿病高危人群，建议从10岁开始或青春期开始时进行糖尿病筛查，首次筛查结果正常者，建议至少每3年重复筛查一次');


INSERT INTO `user` (`id`,`mobile`,`name`,`age`,`gender`,`role_id`) VALUES (1,'13112345678','Tester',20,'M',NULL);
